import './globals.css'
import Header from "./Header";

export const metadata = {
  title: 'Valorant Strategy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  )
}
